apiVersion: v1
kind: Service
metadata:
  name: eb-reproducer-app
  labels:
    app: eb-reproducer-app
    runtime: java
spec:
  type: LoadBalancer
  selector:
    app: eb-reproducer-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eb-reproducer-app
  labels:
    app: eb-reproducer-app
    runtime: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eb-reproducer-app
  template:
    metadata:
      labels:
        app: eb-reproducer-app
        runtime: java
    spec:
      containers:
      - name: eb-reproducer-app
        image: eb-reproducer-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
